services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: timerbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 123


  backend:
    build: ./Backend/
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      STORAGE_LOCATION: /app/storage
    ports:
      - "8080:8080"
    volumes:
      - media_data:/app/storage
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./Frontend/
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  media_data:
