CREATE TABLE tb_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE tb_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    cover_url VARCHAR(255),
    release_year INTEGER
);

CREATE TABLE tb_movie_category (
    movie_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (movie_id, category_id),
    CONSTRAINT fk_movie_category_movie FOREIGN KEY (movie_id) REFERENCES tb_movies(id) ON DELETE CASCADE,
    CONSTRAINT fk_movie_category_category FOREIGN KEY (category_id) REFERENCES tb_categories(id) ON DELETE CASCADE
);

CREATE TABLE tb_series_category (
    series_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (series_id, category_id),
    CONSTRAINT fk_series_category_series FOREIGN KEY (series_id) REFERENCES tb_series(id) ON DELETE CASCADE,
    CONSTRAINT fk_series_category_category FOREIGN KEY (category_id) REFERENCES tb_categories(id) ON DELETE CASCADE
);
