CREATE TABLE tb_episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    episode_number INTEGER NOT NULL,
    datapath VARCHAR(255) NOT NULL,
    series_id BIGINT NOT NULL,
    CONSTRAINT uk_series_episode_number UNIQUE (series_id, episode_number),
    CONSTRAINT fk_episode_series FOREIGN KEY (series_id) REFERENCES tb_series(id) ON DELETE CASCADE
);
