const tmdb = (path, size = 'w780') => `https://image.tmdb.org/t/p/${size}${path}`

export const catalog = [
  {
    id: 'interstellar',
    title: 'Interestelar',
    year: '2014',
    rating: '10',
    duration: '2h 49min',
    genre: 'Ficção científica',
    match: '98% relevante',
    description: 'Quando a Terra se torna inabitável, um grupo de exploradores atravessa um buraco de minhoca em busca de um novo lar para a humanidade.',
    image: tmdb('/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'),
    hero: tmdb('/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg', 'original'),
    accent: '#8b765e',
    categories: ['Filmes', 'Ficção e suspense'],
  },
  {
    id: 'breaking-bad',
    title: 'Breaking Bad',
    year: '2008',
    rating: '18',
    duration: '5 temporadas',
    genre: 'Drama criminal',
    match: '99% relevante',
    description: 'Um professor de química diagnosticado com câncer entra no mundo do crime para garantir o futuro de sua família.',
    image: tmdb('/ggFHVNu6YYI5L9pCfOacjizRGt.jpg'),
    hero: tmdb('/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg', 'original'),
    accent: '#58754b',
    categories: ['Séries', 'Ficção e suspense'],
  },
  {
    id: 'better-call-saul',
    title: 'Better Call Saul',
    year: '2015',
    rating: '16',
    duration: '6 temporadas',
    genre: 'Drama criminal',
    match: '98% relevante',
    description: 'Antes de se tornar Saul Goodman, Jimmy McGill era um advogado tentando encontrar seu lugar no mundo.',
    image: tmdb('/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg'),
    accent: '#b8683e',
    categories: ['Séries'],
  },
  {
    id: 'dark',
    title: 'Dark',
    year: '2017',
    rating: '16',
    duration: '3 temporadas',
    genre: 'Mistério',
    match: '97% relevante',
    description: 'O desaparecimento de uma criança expõe os segredos de quatro famílias e um mistério que atravessa gerações.',
    image: tmdb('/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg'),
    accent: '#46606f',
    categories: ['Séries', 'Ficção e suspense'],
  },
  {
    id: 'the-walking-dead',
    title: 'The Walking Dead',
    year: '2010',
    rating: '16',
    duration: '11 temporadas',
    genre: 'Terror',
    match: '96% relevante',
    description: 'Sobreviventes enfrentam mortos-vivos e conflitos humanos em um mundo devastado.',
    image: tmdb('/n7PVu0hSz2sAsVekpOIoCnkWlbn.jpg'),
    accent: '#756249',
    categories: ['Séries', 'Ficção e suspense'],
  },
  {
    id: 'stranger-things',
    title: 'Stranger Things',
    year: '2016',
    rating: '14',
    duration: '4 temporadas',
    genre: 'Ficção científica',
    match: '95% relevante',
    description: 'Um grupo de amigos encontra forças sobrenaturais e experimentos secretos em uma pequena cidade.',
    image: tmdb('/49WJfeN0moxb9IPfGn8AIqMGskD.jpg'),
    accent: '#8e3333',
    categories: ['Séries', 'Ficção e suspense'],
  },
  {
    id: 'the-last-of-us',
    title: 'The Last of Us',
    year: '2023',
    rating: '16',
    duration: '2 temporadas',
    genre: 'Drama',
    match: '96% relevante',
    description: 'Joel e Ellie atravessam uma América pós-apocalíptica em uma jornada brutal e profundamente humana.',
    image: tmdb('/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg'),
    accent: '#596350',
    categories: ['Séries'],
  },
  {
    id: 'inception',
    title: 'A Origem',
    year: '2010',
    rating: '14',
    duration: '2h 28min',
    genre: 'Ficção científica',
    match: '98% relevante',
    description: 'Um ladrão capaz de invadir sonhos recebe a missão impossível de implantar uma ideia na mente de um herdeiro.',
    image: tmdb('/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg'),
    accent: '#536475',
    categories: ['Filmes', 'Ficção e suspense'],
  },
  {
    id: 'spider-verse',
    title: 'Homem-Aranha: Através do Aranhaverso',
    year: '2023',
    rating: '10',
    duration: '2h 20min',
    genre: 'Animação',
    match: '97% relevante',
    description: 'Miles Morales atravessa o multiverso e encontra uma equipe de Pessoas-Aranha encarregada de proteger sua existência.',
    image: tmdb('/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg'),
    accent: '#a44669',
    categories: ['Filmes'],
  },
  {
    id: 'dune-part-two',
    title: 'Duna: Parte Dois',
    year: '2024',
    rating: '14',
    duration: '2h 46min',
    genre: 'Ficção científica',
    match: '96% relevante',
    description: 'Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os responsáveis pela queda de sua família.',
    image: tmdb('/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg'),
    accent: '#c17743',
    categories: ['Filmes', 'Ficção e suspense'],
  },
  {
    id: 'oppenheimer',
    title: 'Oppenheimer',
    year: '2023',
    rating: '16',
    duration: '3h',
    genre: 'Drama histórico',
    match: '95% relevante',
    description: 'A trajetória do físico J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.',
    image: tmdb('/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'),
    accent: '#a25937',
    categories: ['Filmes'],
  },
  {
    id: 'the-batman',
    title: 'Batman',
    year: '2022',
    rating: '14',
    duration: '2h 56min',
    genre: 'Ação',
    match: '94% relevante',
    description: 'Batman investiga uma série de crimes que revela a corrupção nas estruturas mais poderosas de Gotham.',
    image: tmdb('/74xTEgt7R36Fpooo50r9T25onhq.jpg'),
    accent: '#9b3030',
    categories: ['Filmes', 'Ficção e suspense'],
  },
  {
    id: 'matrix',
    title: 'Matrix',
    year: '1999',
    rating: '14',
    duration: '2h 16min',
    genre: 'Ficção científica',
    match: '97% relevante',
    description: 'Um programador descobre que o mundo que conhece é uma simulação e passa a lutar pela liberdade humana.',
    image: tmdb('/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg'),
    accent: '#477150',
    categories: ['Filmes', 'Ficção e suspense'],
  },
]

export const rows = [
  { title: 'Séries essenciais', subtitle: 'Histórias para começar e não conseguir parar', category: 'Séries' },
  { title: 'Filmes inesquecíveis', subtitle: 'Grandes histórias para a sua próxima sessão', category: 'Filmes' },
  { title: 'Suspense e ficção', subtitle: 'Realidades que desafiam tudo o que você conhece', category: 'Ficção e suspense' },
  { title: 'Novidades do catálogo', subtitle: 'Títulos adicionados recentemente à plataforma', category: 'Novidades' },
]
